USE [BD_GestionTickets]
GO

/****** Object:  Table [dbo].[t_ruc]    Script Date: 16/07/2017 13:06:46 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[t_ruc](
	[cod_cli] [varchar](50) NOT NULL,
	[ruc_cli] [varchar](11) NULL,
 CONSTRAINT [PK_ruc] PRIMARY KEY CLUSTERED 
(
	[cod_cli] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


